### ISSUE TITLE
CRM1-21 WS validateUserApp parámetro validaAplicacion- No muestra mensaje de error Tipo de dato inválido

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#10]
Se ejecuta el WS validateUserApp con el parámetro validaAplicacion con valor  el WS responde "Bad Request". Se espera que el sistema muestre el detalle de la condición de error presentada, es decir que informe que el parámetro contiene tipo de dato invalido.
[CPCRM1-21_Ws Auntenticación de colaboradores.docx](https://github.com/sgcollazos/IntegracionesCRM/files/3843439/CPCRM1-21_Ws.Auntenticacion.de.colaboradores.docx)

**Comment by bryrodriguez** [comment]
El error presentado es el que controla spring por medio del rest-api, al ser un control de ingreso no se adiciono un mensaje personalizado.

**Comment by brebrito** [comment]
De acuerdo a respuesta se anula el hallazgo.
