### ISSUE TITLE
CRM5- Crea tenencias con codigo_producto no existente

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#17]
Se realiza la creación de tenencias en el Stage de cada empresa (coo, sal, pro, fin, fidu) con codigo_producto no existente en el MCD y la ETL Cargue Tenencia de productos realiza el cargue exitoso de la tenencia en el MCD. Se espera que la ETL solo cargue las tenencias que tengan ente_acumulador y codigo_producto existentes en el MCD.
![Image 166](https://user-images.githubusercontent.com/57678779/69977159-4331bf00-14f8-11ea-946c-f13c995e8813.png)

**Comment by danfrancocas** [comment]
Se procede a realizar cambio en la ETL para validación de productos correctamente

**Comment by brebrito** [comment]
Se valida y se encuentra solucionado.
