### ISSUE TITLE
CRM21- Parámetros de salida con valores inconsistentes

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#21]
Se evidencia que al ejecutar el WS ACTUALIZACIÓN DE DATOS DE CLIENTE EN GOLDEN RECORD, los parámetros de salida que retorna el WS contiene valores inconsistentes. Se espera que los valores sean los siguientes:
- ResponseCode: Código de la respuesta
- ResponseDesc: Descripción de la respuesta
- codRepuesta: Código de respuesta 0 exitoso diferente de 0 es un error
- idCorrelacion: ID único de la transacción generado desde el Golden Record
- codigoError: Respuesta a una situación normalizada presentada durante un proceso de sincronización.
- descripcionError: Descripción de la respuesta asociada a una situación normalizada y presentada durante un proceso de sincronización.
- numeroUnicoAsociado: Número de identificación del asociado.

![Image 012](https://user-images.githubusercontent.com/57678779/71589655-a0b72c80-2af3-11ea-8497-9e6c19e95626.png)

**Comment by brero12** [comment]
Se valida la existencia de los campos, adicional se valida que el campo idCorrelacion sea el entregado por Golden

**Comment by brebrito** [comment]
Se informa al área funcional de Coomeva la respuesta de golden debido a que idcorrelaccion no corresponde idunicotransaccion y numerounicoasociado no corresponde idasociado, según lo solicitado en el requerimiento.
