### ISSUE TITLE
CRM21- No muestra listado de errores al enviar campos vacíos

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#24]
Se evidencia que al ejecutar el WS ACTUALIZACIÓN DE DATOS DE CLIENTE EN GOLDEN RECORD, con los parámetros de entrada vacíos, el sistema muestra el mensaje "Internal Server Error", se espera que al enviar estos valores el WS retorne el listado de errores como se describe en el requerimiento "Si durante la sincronización de un asociado, se presentan múltiples errores, la respuesta debe entregar un listado con todos los problemas presentados."

![Image 4](https://user-images.githubusercontent.com/57678779/71592767-85eab500-2aff-11ea-9b4f-4e85ae5ad156.png)

**Comment by brero12** [comment]
Se realiza validación de campos obligatorios y opcionales.

**Comment by brebrito** [comment]
Se realiza el reproceso y se evidencia que se encuentra solucionado.

![image](https://user-images.githubusercontent.com/57678779/72388472-0dd1e100-36f4-11ea-9a35-02ddb5514a2b.png)

![image](https://user-images.githubusercontent.com/57678779/72388480-12969500-36f4-11ea-9649-3bfdcbfb9191.png)
