### ISSUE TITLE
CRM21- No muestra listado de errores al validar parametros con longitud máxima

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#25]
Se evidencia que al ejecutar el WS ACTUALIZACIÓN DE DATOS DE CLIENTE EN GOLDEN RECORD, y al superar la cantidad máxima de caracteres del campo departamentoCorrespondencia, el sistema muestra el siguiente mensaje ""Error general. [ORA-06502". Se espera que el WS muestre el listado de errores e informe el campo que presenta el error.

![Image 6](https://user-images.githubusercontent.com/57678779/71593878-aae12700-2b03-11ea-8c5f-99fd3d3fc5d8.png)

**Comment by brero12** [comment]
Se realiza validación de longitudes de campos obligatorios y opcionales,

**Comment by brebrito** [comment]
Se realiza el reproceso y se evidencia que se encuentra solucionado.

![image](https://user-images.githubusercontent.com/57678779/72560970-210cba00-3876-11ea-9bad-a29a1dbc3958.png)
