### ISSUE TITLE
CRM21- No muestra error al enviar parámetros con tipo de dato inválido

### ISSUE THREAD

**Issue by brebrito** [sgcollazos/IntegracionesCRM#26]
Se evidencia que al ejecutar el WS ACTUALIZACIÓN DE DATOS DE CLIENTE EN GOLDEN RECORD e ingresar el valor "c" en el campo idAsociado, el sistema muestra el mensaje "Bad Request". Se espera que el WS muestre el error informando que el campo contiene tipo de dato es inválido".

![Image 7](https://user-images.githubusercontent.com/57678779/71594070-643ffc80-2b04-11ea-8149-c0308ccd0224.png)

**Comment by brero12** [comment]
La validación de tipos de datos inicialmente la realiza spring por ello el mensaje visualizado es un mensaje genérico de tipo de dato invalido.
